### ISSUE TITLE
world scale

### ISSUE THREAD

**Issue by nickyb78** [Nibre/MotherVR#12] opened 2017-08-01 11:35 UTC
Love i can now play this in vr. The only issue i have is everything looks a little of scale, like its a bit squashed lol. Still love the experience though. Hopefully some kind of tweaking on the scaling will be added in the future

**Comment by bakman2** [comment] 2017-08-02 06:24
Change your IPD setting on your HMD.

**Comment by nickyb78** [comment] 2017-08-02 09:08
It helps a little. I found adjusting the way im sitting helps as well. My head was just about touching the door frames in the game before but if i sit a little lower im about the right hight in the game world and everything looks better sitting at a lower hight as well

**Comment by kvdv99** [comment] 2017-08-09 20:49
yes, everything looks squashed, I agree, hope it can be fixed with a future version..

**Comment by Nibre** [comment] 2017-08-27 07:55
Scale is tricky to perceive in this game, as your character’s small, space-stations are cramped, and VR skews floor perception when sitting.

From everything that I can tell, the scale is perfectly matched to the objects in the game. Headset IPD is what will greatly affect your perception of scale, so make sure that you have it set correctly, and keep in mind spaceships are supposed to feel cramped.

**Comment by Nibre** [comment] 2017-09-07 12:00
Closing this as a duplicate of #1 , to consolidate issues.

**Closed by Nibre** 2017-09-07 12:00 UTC
Labels: duplicate
