### ISSUE TITLE
Keyboard/Mouse: Unable to change weapons & craft

### ISSUE THREAD

**Issue by Hunterfx21** [Nibre/MotherVR#33] opened 2017-08-27 05:21 UTC
As the title says,
When you press 'Q' to open your HUD, you are unable to select a new item/weapon.

I first noticed this during the start of the game when I was trying to craft a medkit, because that's all that was in my inventory at the time.

With the HUD following your head, there's no way to select another option... at least on keyboard and mouse.

**Comment by willibeu** [comment] 2017-08-27 12:18
Same problem here...only able to pick two items from the selection circle with Mouse keyboard.  Would rather not use xbox controller

**Comment by Nibre** [comment] 2017-08-27 12:21
Yea, it has to do with the scale of the game window (for the mouse) being way smaller than how large VR renders it. For the Weapon Menu specifically, it seems to only be the top-left quarter of the screen it can move to. This is something I will be looking into, but not sure how long it will take to fix.

**Comment by Hunterfx21** [comment] 2017-08-27 16:50
Well, I'll just consider it an extra "challenge" mode for now, haha.

Thank you for all you've done!

**Comment by GTRSeriousSam** [comment] 2017-09-10 09:36
This is the only thing that's making this unplayable for M&K on the Vive. Loaded up an end game save and I could only access my top left items.

**Comment by budwheizzah** [comment] 2018-04-15 08:30
You're supposed to aim vertically with your head. Having the mouse move the vertical axis would result in improper VR possibly causing motion sickness. The current aim scheme works as intended like any first party seated VR. For the crafting menu, highly suggest having a gamepad plugged in even when you play with M&KB as it allows to access all the functions quickly (all while not needing to give up M&KB of course)

**Comment by Nibre** [comment] 2018-06-11 23:34
This has been fixed in the latest [Release](https://github.com/Nibre/MotherVR/releases). I also included another improvement in that menu, that you may notice 😉

**Closed by Nibre** 2018-06-11 23:34 UTC
Labels: bug, fixed
