### ISSUE TITLE
Point of view calibration

### ISSUE THREAD

**Issue by sardo77** [Nibre/MotherVR#15] opened 2017-08-03 12:49 UTC
While playing i've discovered the issue when you interact with the devices - computers or ladders or door locking mechanism your point of view got fixed sometimes in the wrong direction - sideway or back. Is there a way to calibrate your point of view in the game?

**Comment by baggyg** [comment] 2017-08-03 12:56
I believe this occurs when you use your head to turn and don't interact with these things head on (to your in -game body). Is that correct?

**Comment by sardo77** [comment] 2017-08-03 13:02
No it happens when I interact with these things standing straight on before them looking directly at them. LB+RB doesn't fix it as it seems only fix distance to the computers screen to avoid blackness.

**Comment by stenyak** [comment] 2017-08-05 11:02
I also experience the same issue: interacting with these objects, as well as entering ventilation shafts, resets the camera rotation to the "forward" orientation (the one used as forward for the Oculus Home 3d environment).

After this happens, I need to manually rotate the character again so it points back where it was pointing before using the devices/shafts/stairs.

To reproduce, you can for example recalibrate the Oculus sensors, and when it asks you to point the Touch controller to your screen, simply point somewhere else. The Oculus Home will then be oriented there, rather than towards your computer. Then you will easily notice how the bug behaves in Alien Isolation.
Alternatively, instead of recalibrating, move your keyboard/mouse with you as you rotate on your real life chair 90deg to the left, and play like that.

**Comment by jonnypanic** [comment] 2017-08-28 03:16
I get this issue too, using a Pimax. With the Pimax I think the issue is caused or exacerbated by the annoying gyro drift problem the Pimax has at the moment. Recentering with the Pimax software should work, but not for very long. The above suggestion works well enough for now though, cheers.

**Comment by Nibre** [comment] 2017-09-07 12:04
Rotation thing is known and is being worked on

**Comment by Nibre** [comment] 2018-06-11 23:16
Rotation calibration has been fixed in the latest [Release](https://github.com/Nibre/MotherVR/releases) 😎

**Closed by Nibre** 2018-06-11 23:16 UTC
Labels: bug, fixed
